### ISSUE TITLE
This was take from

### ISSUE THREAD

**Issue by TheKnightGamer** [MCrafterss/CosmeticMenu#1]
This is taken from ImagicalDevs no one allowed you to take this plugin please put it back.

**Comment by LittleBigMC** [comment]
No i put it there. I am also part of this organisation and i want to
publish it here. Maybe delete from imagicaldevs

**Comment by TheKnightGamer** [comment]
OK confirmed you are part of team if you move it it is alright have a nice day and next time ask.

**Comment by LittleBigMC** [comment]
I am part of three teams. I want to keep it here and at your so we can get
different ideas

**Comment by TheKnightGamer** [comment]
Why not ask people for ideas and we can put this plugin in a lot of organization but don't delete it from ImagicalDevs that is where the main plugin was found.

**Comment by LittleBigMC** [comment]
No i said that if i have to (if u want me to) i can delete it from either
organisation. But i really want to keep it at both

**Comment by Taki21** [comment]
@TheKnightGamer This was @LittleBigMC 's Idea to make this plugin so let him decide what he wants to do with it. I know how we all want cool plugins on this organization However, If he created it, he has more permission over it then anybody else.

**Comment by TheKnightGamer** [comment]
I give up on plugin development.

**Comment by Taki21** [comment]
um ... ok if u want? why though?

**Comment by Taki21** [comment]
Oops wrong repo xD

**Comment by LittleBigMC** [comment]
Thanks and also i decided to keep it at both

**Comment by TheDragonRing** [comment]
XD true, @TheKnightGamer you can't stop it, but just because you can't stop this doesn't mean stop plugin devving

**Comment by TheKnightGamer** [comment]
No not because of this it because I never get thing right.

**Comment by iPocket** [comment]
@LittleBigMC, @TheKnightGamer is right, delete this repo yourself.

**Comment by Taki21** [comment]
This is not fully imagicaldevs' plugin as @LittleBigMC is the owner of this repo
